INSERT INTO Appareil VALUES (1,'Cannon','IXUS');
INSERT INTO Appareil VALUES (2,'Hasselblad','1600F');
INSERT INTO Appareil VALUES (3,NULL,'PEN E-P1');
INSERT INTO Appareil VALUES (4,'Nikon','F');
INSERT INTO Appareil VALUES (5,'Leica','I');

INSERT INTO Configuration VALUES(1,1,1.8,15,'off',200);
INSERT INTO Configuration VALUES(2,3,11,500,'manual',26);
INSERT INTO Configuration VALUES(3,2,5.6,1,'auto',100);
INSERT INTO Configuration VALUES(4,5,22,30,'off',58);
INSERT INTO Configuration VALUES(5,4,4,8,'auto',40);
INSERT INTO Configuration VALUES(6,1,1.4,4,'auto',85);

INSERT INTO Dates VALUES(1,TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(2,TO_DATE('2003/05/04 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(3,TO_DATE('2019/12/24 11:42:57', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(4,TO_DATE('2019/12/26 11:42:57', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(5,TO_DATE('2020/07/03 12:37:27', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(6,TO_DATE('2020/07/06 12:37:27', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(7,TO_DATE('2017/03/13 14:02:07', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(8,TO_DATE('2017/04/17 14:02:07', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(9,TO_DATE('2014/06/21 15:36:25', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(10,TO_DATE('2014/06/22 15:36:25', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(11,TO_DATE('2015/02/1 15:46:52', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO Dates VALUES(12,TO_DATE('2015/02/3 15:36:25', 'yyyy/mm/dd hh24:mi:ss'));

INSERT INTO Lieu VALUES (1, 43.6112422, 3.8767337, 'Montpellier', 'Hérault', 'France', '34000');
INSERT INTO Lieu VALUES (2, 45.7578137, 4.8320114,  'Lyon', 'Rhône-Alpe', 'France', '69000');
INSERT INTO Lieu VALUES (3, 44.8178131, 20.4568974, 'Belgrade', NULL, 'Serbie', NULL);
INSERT INTO Lieu VALUES (4, 51.44289578004158,-0.1598961199024851, 'Londres', 'undefined', ' Royaume-Uni', '75000'  );
INSERT INTO Lieu VALUES (5, 42.3788774, -72.032366, 'Massachusetts', NULL, 'United-States',NULL);

INSERT INTO Utilisateur VALUES (1);
INSERT INTO Utilisateur VALUES (2);
INSERT INTO Utilisateur VALUES (3);
INSERT INTO Utilisateur VALUES (4);
INSERT INTO Utilisateur VALUES (5);
INSERT INTO Utilisateur VALUES (6);

INSERT INTO Abonne VALUES (1,3);
INSERT INTO Abonne VALUES (3,2);
INSERT INTO Abonne VALUES (2,4);
INSERT INTO Abonne VALUES (4,1);
INSERT INTO Abonne VALUES (1,6);
INSERT INTO Abonne VALUES (4,6);
INSERT INTO Abonne VALUES (6,4);

INSERT INTO ContenuNumerique VALUES (1);
INSERT INTO ContenuNumerique VALUES (2);
INSERT INTO ContenuNumerique VALUES (3);
INSERT INTO ContenuNumerique VALUES (4);
INSERT INTO ContenuNumerique VALUES (5);
INSERT INTO ContenuNumerique VALUES (6);
INSERT INTO ContenuNumerique VALUES (7);
INSERT INTO ContenuNumerique VALUES (8);
INSERT INTO ContenuNumerique VALUES (9);
INSERT INTO ContenuNumerique VALUES (10);
INSERT INTO ContenuNumerique VALUES (11);
INSERT INTO ContenuNumerique VALUES (12);
INSERT INTO ContenuNumerique VALUES (13);
INSERT INTO ContenuNumerique VALUES (14);
INSERT INTO ContenuNumerique VALUES (15);
INSERT INTO ContenuNumerique VALUES (16);
INSERT INTO ContenuNumerique VALUES (17);
INSERT INTO ContenuNumerique VALUES (18);
INSERT INTO ContenuNumerique VALUES (19);
INSERT INTO ContenuNumerique VALUES (20);
INSERT INTO ContenuNumerique VALUES (21);
INSERT INTO ContenuNumerique VALUES (22);
INSERT INTO ContenuNumerique VALUES (23);
INSERT INTO ContenuNumerique VALUES (24);
INSERT INTO ContenuNumerique VALUES (25);
INSERT INTO ContenuNumerique VALUES (26);
INSERT INTO ContenuNumerique VALUES (27);
INSERT INTO ContenuNumerique VALUES (28);
INSERT INTO ContenuNumerique VALUES (29);
INSERT INTO ContenuNumerique VALUES (30);
INSERT INTO ContenuNumerique VALUES (31);
INSERT INTO ContenuNumerique VALUES (32);
INSERT INTO ContenuNumerique VALUES (33);
INSERT INTO ContenuNumerique VALUES (34);
INSERT INTO ContenuNumerique VALUES (35);
INSERT INTO ContenuNumerique VALUES (36);
INSERT INTO ContenuNumerique VALUES (37);
INSERT INTO ContenuNumerique VALUES (38);
INSERT INTO ContenuNumerique VALUES (39);
INSERT INTO ContenuNumerique VALUES (40);
INSERT INTO ContenuNumerique VALUES (41);

INSERT INTO CollectionPhotos VALUES(1);
INSERT INTO CollectionPhotos VALUES(2);
INSERT INTO CollectionPhotos VALUES(3);
INSERT INTO CollectionPhotos VALUES(4);
INSERT INTO CollectionPhotos VALUES(5);
INSERT INTO CollectionPhotos VALUES(6);
INSERT INTO CollectionPhotos VALUES(7);
INSERT INTO CollectionPhotos VALUES(8);
INSERT INTO CollectionPhotos VALUES(9);
INSERT INTO CollectionPhotos VALUES(10);

INSERT INTO Album VALUES(1,1);
INSERT INTO Album VALUES(2,2);
INSERT INTO Album VALUES(3,3);
INSERT INTO Album VALUES(4,4);
INSERT INTO Album VALUES(5,5);

INSERT INTO Galerie VALUES(6,1);
INSERT INTO Galerie VALUES(7,2);
INSERT INTO Galerie VALUES(8,3);
INSERT INTO Galerie VALUES(9,4);
INSERT INTO Galerie VALUES(10,5);

INSERT INTO Photographie VALUES(1,'TousDroitsReserves',1,1,2,1,1,1);
INSERT INTO Photographie VALUES(2,'ModificationImageAutorisee',2,3,4,1,2,2);
INSERT INTO Photographie VALUES(3,'UtilisationCommercialeAutorisee',3,5,6,1,3,3);
INSERT INTO Photographie VALUES(4,'TousDroitsReserves',4,7,8,1,4,4);
INSERT INTO Photographie VALUES(5,'TousDroitsReserves',5,9,10,1,5,5);
INSERT INTO Photographie VALUES(6,'UtilisationCommercialeAutorisee',1,11,12,5,6,NULL);

INSERT INTO Tag VALUES(1,'vacation',1,1);
INSERT INTO Tag VALUES(2,'fun',1,1);
INSERT INTO Tag VALUES(3,'love',1,1);
INSERT INTO Tag VALUES(4,'vacation',2,2);
INSERT INTO Tag VALUES(5,'love',3,3);
INSERT INTO Tag VALUES(6,'discovery',4,4);
INSERT INTO Tag VALUES(7,'vacation',4,4);
INSERT INTO Tag VALUES(8,'paris',4,4);
INSERT INTO Tag VALUES(9,'relatable',5,5);
INSERT INTO Tag VALUES(10,'studying',1,6);
INSERT INTO Tag VALUES(11,'smart',1,6);

INSERT INTO Contient VALUES(1,1);
INSERT INTO Contient VALUES(2,2);
INSERT INTO Contient VALUES(3,3);
INSERT INTO Contient VALUES(4,4);
INSERT INTO Contient VALUES(5,5);
INSERT INTO Contient VALUES(6,1);
INSERT INTO Contient VALUES(1,3);
INSERT INTO Contient VALUES(2,5);
INSERT INTO Contient VALUES(3,4);
INSERT INTO Contient VALUES(4,2);
INSERT INTO Contient VALUES(5,1);
INSERT INTO Contient VALUES(1,2);




INSERT INTO Aime VALUES(5,1);
INSERT INTO Aime VALUES(1,1);
INSERT INTO Aime VALUES(6,3);
INSERT INTO Aime VALUES(3,1);
INSERT INTO Aime VALUES(6,1);
INSERT INTO Aime VALUES(2,4);
INSERT INTO Aime VALUES(6,5);
INSERT INTO Aime VALUES(2,6);
INSERT INTO Aime VALUES(2,3);
INSERT INTO Aime VALUES(1,5);
INSERT INTO Aime VALUES(4,1);
INSERT INTO Aime VALUES(3,3);
INSERT INTO Aime VALUES(6,2);
INSERT INTO Aime VALUES(1,2);
INSERT INTO Aime VALUES(1,4);
INSERT INTO Aime VALUES(2,1);
INSERT INTO Aime VALUES(3,6);
INSERT INTO Aime VALUES(3,4);
INSERT INTO Aime VALUES(2,5);
INSERT INTO Aime VALUES(5,5);
INSERT INTO Aime VALUES(5,4);

INSERT INTO Discussion VALUES(1,1);
INSERT INTO Discussion VALUES(2,2);
INSERT INTO Discussion VALUES(3,3);
INSERT INTO Discussion VALUES(4,5);
INSERT INTO Discussion VALUES(5,5);

INSERT INTO Commentaire VALUES(7,3,6,'an what like spot. Pressed my by');
INSERT INTO Commentaire VALUES(8,5,3,'imagine at forbade. At name no');
INSERT INTO Commentaire VALUES(9,2,5,'Mrs can hundred its greater account. Distrusts daughters');
INSERT INTO Commentaire VALUES(10,4,4,'handsome. Up do view time they');
INSERT INTO Commentaire VALUES(11,2,1,'men drew its post knew. Of talking');
INSERT INTO Commentaire VALUES(12,5,2,'entered the examine. Blessing scarcely confined her contempt wondered shy. Dashwoods contented');
INSERT INTO Commentaire VALUES(13,5,3,'be projection possession of. Real no near room ye bred');
INSERT INTO Commentaire VALUES(14,4,4,'last upon he same as knew next. Of believed or diverted');
INSERT INTO Commentaire VALUES(15,2,1,'man garrets. Common indeed garden');
INSERT INTO Commentaire VALUES(16,5,6,'increasing led day sympathize yet.');
INSERT INTO Commentaire VALUES(17,1,4,'use. Sure last upon he');
INSERT INTO Commentaire VALUES(18,4,3,'hung am size spot no. Likewise led and dissuade');
INSERT INTO Commentaire VALUES(19,1,4,'draw. Mistake totally of in chiefly. Justice visitor him entered for. Continue');
INSERT INTO Commentaire VALUES(20,2,6,'females so improve in picture. Mrs can hundred its greater account.');
INSERT INTO Commentaire VALUES(21,3,4,'estimating are motionless day sentiments end. Calling an imagine at forbade.');
INSERT INTO Commentaire VALUES(22,1,6,'request charmed me warrant to. Expect');
INSERT INTO Commentaire VALUES(23,5,3,'As game he show it park do.');
INSERT INTO Commentaire VALUES(24,2,4,'end sister except oppose. Endeavor bachelor but add');
INSERT INTO Commentaire VALUES(25,5,5,'talent. Sociable formerly six but handsome. Up do view time');
INSERT INTO Commentaire VALUES(26,5,5,'Of regard warmth by unable sudden garden');
INSERT INTO Commentaire VALUES(27,1,5,'in chiefly. Justice visitor him entered for. Continue delicate as unlocked entirely');
INSERT INTO Commentaire VALUES(28,3,3,'of calling however civilly wishing resolve.');
INSERT INTO Commentaire VALUES(29,2,4,'resolve.');
INSERT INTO Commentaire VALUES(30,1,5,'discourse see led collected. Packages oh no denoting');
INSERT INTO Commentaire VALUES(31,2,4,'reasonable be projection possession of. Real no near');
INSERT INTO Commentaire VALUES(32,2,4,'observe fortune norland. Hunted mrs ham wishes stairs. Continued');
INSERT INTO Commentaire VALUES(33,2,3,'do be so he enough talent. Sociable formerly');
INSERT INTO Commentaire VALUES(34,3,4,'do though so genius afraid cousin. Girl when');
INSERT INTO Commentaire VALUES(35,5,5,'projection possession of. Real no near room ye');
INSERT INTO Commentaire VALUES(36,1,5,'would still if to. Position boy required law moderate was');
INSERT INTO Commentaire VALUES(37,1,6,'calling however civilly wishing resolve.');
INSERT INTO Commentaire VALUES(38,4,4,'though so genius afraid cousin. Girl when');
INSERT INTO Commentaire VALUES(39,4,5,'be so he enough talent. Sociable formerly six');
INSERT INTO Commentaire VALUES(40,2,1,'use. Sure last upon he same as knew next. Of believed or');